"""add primary keys to profile_requests and user_request_log

Revision ID: a1022b09505d
Revises: 
Create Date: 2025-06-17 22:31:11.016739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1022b09505d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_users',
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('blocked_at', sa.Integer(), nullable=True),
    sa.Column('is_bot', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('bug_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=True),
    sa.Column('target_username', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('enqueued_ts', sa.Integer(), nullable=True),
    sa.Column('processed_ts', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('task_details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invalid_link_violations',
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('suspended_until', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('monitor_sent_stories',
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('monitor_id', 'story_id')
    )
    op.create_table('monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=True),
    sa.Column('target_username', sa.String(), nullable=True),
    sa.Column('last_checked', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_requests',
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('target_username', sa.String(), nullable=False),
    sa.Column('requested_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id', 'target_username')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('task_details', sa.String(), nullable=True),
    sa.Column('enqueued_ts', sa.Integer(), nullable=True),
    sa.Column('is_premium', sa.Integer(), nullable=True),
    sa.Column('is_bot', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('target_username', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_request_log',
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('requested_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', 'requested_at')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('is_bot', sa.Integer(), nullable=True),
    sa.Column('is_premium', sa.Integer(), nullable=True),
    sa.Column('free_trial_used', sa.Integer(), nullable=True),
    sa.Column('premium_until', sa.Integer(), nullable=True),
    sa.Column('pinned_message_id', sa.Integer(), nullable=True),
    sa.Column('pinned_message_updated_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_request_log')
    op.drop_table('tasks')
    op.drop_table('profile_requests')
    op.drop_table('monitors')
    op.drop_table('monitor_sent_stories')
    op.drop_table('invalid_link_violations')
    op.drop_table('download_queue')
    op.drop_table('bug_reports')
    op.drop_table('blocked_users')
    # ### end Alembic commands ###
