"""update seqs

Revision ID: a4d1be680c25
Revises: 83f1e3033337
Create Date: 2025-06-20 09:02:12.760260

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4d1be680c25"
down_revision: Union[str, Sequence[str], None] = "83f1e3033337"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_chat_id"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_chat_id"), "user", ["chat_id"], unique=False)
    # ### end Alembic commands ###
