"""fixes

Revision ID: bf491788b3b8
Revises: 89f629cc34db
Create Date: 2025-06-20 12:27:19.748689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf491788b3b8'
down_revision: Union[str, Sequence[str], None] = '89f629cc34db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invalid_link_violation',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('suspended_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('download_queue', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.add_column('user', sa.Column('chat_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'user', 'chat', ['chat_id'], ['id'])
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'chat_id')
    op.alter_column('download_queue', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_table('invalid_link_violation')
    # ### end Alembic commands ###
